#!/bin/sh /etc/rc.common

#. /lib/blue-merle/functions.sh

#START=10
#STOP=99

#start(){
#    RANDOMIZE_HOSTNAME
#}
#stop(){
#    echo "Stopping Blue-Merle Hostname Randomize Service"
#}

#!/bin/sh /etc/rc.common
. /lib/blue-merle/functions.sh

START=10
STOP=99
USE_PROCD=1

start() {
    procd_open_instance
    procd_set_param command RANDOMIZE_HOSTNAME
    procd_close_instance
}

stop() {
    echo "Stopping Blue-Merle Hostname Randomize Service"
}

status() {
    # Use procd to check the status
    procd_running RANDOMIZE_HOSTNAME
    if [ $? -eq 0 ]; then
        echo "Running"
    else
        echo "Stopped"
    fi
}
